name: rclone Build

on:
  push:
    branches:
      - feat/rclone-build

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux Binary
        run: make build-linux

      - name: Create ~/.zcn and add wallet.json and config.yaml
        run: |
          mkdir -p ~/.zcn
           printf '%s' "${{ secrets.ZCN_WALLET_JSON }}" | base64 -d > ~/.zcn/wallet.json
           printf '%s' "${{ secrets.ZCN_CONFIG_YAML }}" > ~/.zcn/config.yaml
      - name: Upload wallet.json for debug
        uses: actions/upload-artifact@v4
        with:
          name: wallet-debug
          path: ~/.zcn/wallet.json
      - name: Validate wallet.json
        run: |
          cat ~/.zcn/wallet.json | jq empty

      - name: Setup rclone Configuration
        run: |
          mkdir -p ~/.config/rclone
          printf '%s' "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Functionality Test (Push and List File)
        run: |
          echo "Listing uploaded file:"
          ./rclone lsf automation:workflow

      - name: Upload Built Binary
        uses: actions/upload-artifact@v4
        with:
          name: rclone-linux
          path: ./rclone


  # build-windows:
  #   name: Build Windows Binary
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #     - run: make build-windows-native
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: rclone-windows
  #         path: ./rclone.exe

  # build-mac-amd:
  #   name: Build macOS (Intel)
  #   runs-on: macos-13

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #     - run: go clean -cache -modcache -testcache
  #     - run: make build-mac-amd
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: rclone-mac-amd64
  #         path: ./rclone

  # build-mac-arm:
  #   name: Build macOS (Apple Silicon)
  #   runs-on: macos-14

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #     - run: go clean -cache -modcache -testcache
  #     - run: make build-mac-arm
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: rclone-mac-arm64
  #         path: ./rclone
